import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { AnswerForm, ConnectionStateForm } from "@/components/connection-actions";

export default async function ConnectionsPage() {
  const user = await requireUser();
  const account = await prisma.user.findUnique({ where: { authUserId: user.id }, select: { id: true } });
  const question = await prisma.microQuestion.findFirst({ where: { active: true }, orderBy: { createdAt: "asc" } });
  const connections = account ? await prisma.connection.findMany({ where: { OR: [{ userAId: account.id }, { userBId: account.id }] }, orderBy: { updatedAt: "desc" }, include: { userA: { include: { profile: true } }, userB: { include: { profile: true } }, answers: { include: { question: true } } } }) : [];
  return <main className="profile-shell"><header className="topbar"><Link href="/discover" className="brand">kindred<span>_</span></Link><Link href="/profile" className="button button-quiet">Profile</Link></header><div className="discovery-heading"><p className="eyebrow">Your people</p><h1>Connections with somewhere to go.</h1><p className="lede">When interest is mutual, both answers reveal themselves and the conversation has a place to begin.</p></div><div className="connection-list">{connections.length ? connections.map((connection) => { const other = connection.userAId === account?.id ? connection.userB : connection.userA; const ownAnswer = connection.answers.find((answer) => answer.authorId === account?.id); const revealedAnswers = connection.answers.filter((answer) => answer.revealState === "REVEALED"); return <article className="connection-card" key={connection.id}><div><p className="eyebrow">{connection.state.replaceAll("_", " ").toLowerCase()}</p><h2>{other.profile?.firstName ?? "Someone"}</h2><p className="discovery-context">{other.profile?.city}</p>{revealedAnswers.map((answer) => <div className="revealed-answer" key={answer.id}><small>{answer.question.prompt}</small><p>{answer.answer}</p></div>)}{question && !ownAnswer && <AnswerForm questionId={question.id} connectionId={connection.id} prompt={question.prompt} />}{ownAnswer && revealedAnswers.length === 0 && <p className="discovery-context">Your answer is ready. Their answer reveals when they respond.</p>}</div><div className="connection-actions"><ConnectionStateForm connectionId={connection.id} state="GETTING_TO_KNOW" label="Start getting to know them" /><ConnectionStateForm connectionId={connection.id} state="PAUSE" label="Pause for now" quiet /></div></article>; }) : <div className="empty-state"><p className="eyebrow">No connections yet</p><h2>Your next conversation starts with context.</h2><Link className="button button-primary" href="/discover">See today&apos;s introductions</Link></div>}</div></main>;
}
