"use client";

import { useActionState } from "react";
import { blockUser, proposeDate, recordMeeting, reportUser, respondToDate, setMeetingReadiness } from "@/server/interaction/actions";

type State = { error?: string } | undefined;
export function MeetingReadinessForm({ connectionId }: { connectionId: string }) { const [state, action, pending] = useActionState(setMeetingReadiness, undefined as State); return <form action={action} className="inline-form"><input type="hidden" name="connectionId" value={connectionId} /><input type="hidden" name="state" value="OPEN_TO_MEETING" /><button className="button button-primary" disabled={pending}>{pending ? "Updating..." : "Open to meeting"}</button>{state?.error && <p className="form-error">{state.error}</p>}</form>; }
export function DateProposalForm({ connectionId }: { connectionId: string }) { const [state, action, pending] = useActionState(proposeDate, undefined as State); return <form action={action} className="date-form"><input type="hidden" name="connectionId" value={connectionId} /><label className="field"><span>Something simple</span><select name="activity" required><option value="COFFEE">Coffee</option><option value="WALK">Walk</option><option value="BOOKSTORE">Bookstore</option><option value="CAMPUS_EVENT">Campus event</option><option value="FOOD">Casual food</option><option value="ARCADE">Arcade</option><option value="MUSEUM">Museum</option><option value="PARK">Park</option><option value="LOCAL_EVENT">Local event</option></select></label><label className="field"><span>When</span><input name="startsAt" type="datetime-local" required /></label><label className="field"><span>General public area</span><input name="generalArea" required maxLength={120} placeholder="A neighborhood, not an address" /></label><label className="field"><span>Note <em>optional</em></span><textarea name="note" maxLength={500} rows={2} /></label><button className="button button-primary" disabled={pending}>{pending ? "Suggesting..." : "Suggest this plan"}</button>{state?.error && <p className="form-error">{state.error}</p>}</form>; }
export function DateResponseForm({ datePlanId, status, label }: { datePlanId: string; status: "ACCEPTED" | "ALTERNATIVE_SUGGESTED" | "DECLINED"; label: string }) { const [state, action, pending] = useActionState(respondToDate, undefined as State); return <form action={action}><input type="hidden" name="datePlanId" value={datePlanId} /><input type="hidden" name="status" value={status} /><button className="button button-quiet" disabled={pending}>{pending ? "Updating..." : label}</button>{state?.error && <p className="form-error">{state.error}</p>}</form>; }
export function SafetyForms({ userId }: { userId: string }) { const [reportState, reportAction, reporting] = useActionState(reportUser, undefined as State); const [blockState, blockAction, blocking] = useActionState(blockUser, undefined as State); return <div className="safety-tools"><form action={blockAction}><input type="hidden" name="userId" value={userId} /><button className="button button-quiet" disabled={blocking}>Block</button></form><form action={reportAction}><input type="hidden" name="userId" value={userId} /><select name="category" defaultValue="SAFETY_CONCERN"><option value="SAFETY_CONCERN">Safety concern</option><option value="HARASSMENT">Harassment</option><option value="SPAM">Spam</option><option value="FAKE_PROFILE">Fake profile</option><option value="OTHER">Other</option></select><button className="button button-quiet" disabled={reporting}>Report</button></form>{(reportState?.error || blockState?.error) && <p className="form-error">{reportState?.error || blockState?.error}</p>}</div>; }
export function MeetingFeedback({ connectionId }: { connectionId: string }) { const [state, action, pending] = useActionState(recordMeeting, undefined as State); return <form action={action} className="feedback-form"><input type="hidden" name="connectionId" value={connectionId} /><span className="field-label">After the time passes</span><div className="button-row"><button name="state" value="MET" className="button button-primary" disabled={pending}>We met</button><button name="state" value="DID_NOT_MEET" className="button button-quiet" disabled={pending}>Didn&apos;t meet</button><button name="state" value="PAUSE" className="button button-quiet" disabled={pending}>Pause</button></div>{state?.error && <p className="form-error">{state.error}</p>}</form>; }