"use server";

import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";

const messageSchema = z.object({ conversationId: z.string().min(1).max(64), body: z.string().trim().min(1).max(2000) });
const connectionIdSchema = z.string().cuid();
const dateSchema = z.object({ connectionId: z.string().cuid(), activity: z.enum(["COFFEE", "WALK", "BOOKSTORE", "CAMPUS_EVENT", "FOOD", "ARCADE", "MUSEUM", "PARK", "LOCAL_EVENT"]), startsAt: z.coerce.date(), generalArea: z.string().trim().min(2).max(120), note: z.string().trim().max(500).optional().or(z.literal("")) });
const reportSchema = z.object({ userId: z.string().cuid(), category: z.enum(["HARASSMENT", "SPAM", "FAKE_PROFILE", "SAFETY_CONCERN", "OTHER"]), details: z.string().trim().max(1000).optional().or(z.literal("")) });

async function accountForUser() { const authUser = await requireUser(); const account = await prisma.user.findUnique({ where: { authUserId: authUser.id }, select: { id: true, role: true } }); if (!account) throw new Error("Account not found"); return account; }
async function authorizedConversation(accountId: string, conversationId: string) { const conversation = await prisma.conversation.findUnique({ where: { id: conversationId }, include: { connection: true } }); if (!conversation || ![conversation.connection.userAId, conversation.connection.userBId].includes(accountId) || ["CLOSED", "PAUSE"].includes(conversation.connection.state)) return null; return conversation; }
async function authorizedConnection(accountId: string, connectionId: string) { const connection = await prisma.connection.findUnique({ where: { id: connectionId } }); return connection && [connection.userAId, connection.userBId].includes(accountId) ? connection : null; }

export async function sendMessage(_previousState: { error?: string } | undefined, formData: FormData) {
  const account = await accountForUser(); const parsed = messageSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Messages must be between 1 and 2,000 characters." }; const conversation = await authorizedConversation(account.id, parsed.data.conversationId); if (!conversation) return { error: "This conversation is unavailable." }; await prisma.message.create({ data: { conversationId: conversation.id, senderId: account.id, body: parsed.data.body } }); return { success: true };
}

export async function markConversationRead(conversationId: string) { const account = await accountForUser(); const conversation = await authorizedConversation(account.id, conversationId); if (!conversation) return; await prisma.message.updateMany({ where: { conversationId, senderId: { not: account.id }, status: "SENT" }, data: { status: "READ" } }); }

export async function setMeetingReadiness(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = z.object({ connectionId: connectionIdSchema, state: z.enum(["PAUSE", "OPEN_TO_MEETING", "CLOSED"]) }).safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "That update is not available." }; const connection = await authorizedConnection(account.id, parsed.data.connectionId); if (!connection) return { error: "You cannot update this connection." }; await prisma.connection.update({ where: { id: connection.id }, data: { state: parsed.data.state } }); redirect(`/chat/${connection.id}`); }

export async function proposeDate(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = dateSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success || parsed.data.startsAt <= new Date()) return { error: "Choose a future time and a general public area." }; const connection = await authorizedConnection(account.id, parsed.data.connectionId); if (!connection || connection.state !== "OPEN_TO_MEETING") return { error: "Both people need to be open to meeting first." }; await prisma.datePlan.create({ data: { connectionId: connection.id, proposerId: account.id, activity: parsed.data.activity, startsAt: parsed.data.startsAt, generalArea: parsed.data.generalArea, note: parsed.data.note || null } }); redirect(`/chat/${connection.id}`); }

export async function respondToDate(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = z.object({ datePlanId: z.string().cuid(), status: z.enum(["ACCEPTED", "ALTERNATIVE_SUGGESTED", "DECLINED"]) }).safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "That response is not available." }; const plan = await prisma.datePlan.findUnique({ where: { id: parsed.data.datePlanId }, include: { connection: true } }); if (!plan || plan.proposerId === account.id || ![plan.connection.userAId, plan.connection.userBId].includes(account.id)) return { error: "You cannot respond to this plan." }; await prisma.datePlan.update({ where: { id: plan.id }, data: { status: parsed.data.status } }); redirect(`/chat/${plan.connectionId}`); }

export async function recordMeeting(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = z.object({ connectionId: connectionIdSchema, state: z.enum(["MET", "DID_NOT_MEET", "CONTINUE", "PAUSE", "END_CONNECTION"]) }).safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "That update is not available." }; const connection = await authorizedConnection(account.id, parsed.data.connectionId); const acceptedPlan = connection ? await prisma.datePlan.findFirst({ where: { connectionId: connection.id, status: "ACCEPTED" }, orderBy: { startsAt: "desc" } }) : null; if (!connection || !acceptedPlan || new Date() < acceptedPlan.startsAt) return { error: "Meeting feedback opens after the planned time." }; await prisma.meetingFeedback.upsert({ where: { connectionId_userId: { connectionId: connection.id, userId: account.id } }, update: { outcome: parsed.data.state }, create: { connectionId: connection.id, userId: account.id, outcome: parsed.data.state } }); redirect(`/chat/${connection.id}`); }

export async function blockUser(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = connectionIdSchema.safeParse(formData.get("userId")); if (!parsed.success || parsed.data === account.id) return { error: "That action is not available." }; await prisma.$transaction([prisma.block.upsert({ where: { blockerId_blockedId: { blockerId: account.id, blockedId: parsed.data } }, update: {}, create: { blockerId: account.id, blockedId: parsed.data } }), prisma.connection.updateMany({ where: { OR: [{ userAId: account.id, userBId: parsed.data }, { userAId: parsed.data, userBId: account.id }] }, data: { state: "CLOSED" } })]); return { success: true }; }

export async function reportUser(_previousState: { error?: string } | undefined, formData: FormData) { const account = await accountForUser(); const parsed = reportSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success || parsed.data.userId === account.id) return { error: "Please choose a valid report." }; await prisma.report.create({ data: { reporterId: account.id, reportedId: parsed.data.userId, category: parsed.data.category, details: parsed.data.details || null } }); return { success: true }; }